//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public projet()
        {
            this.Jobs = new HashSet<Job>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int IdP { get; set; }
        public string Titre { get; set; }
        public string Proprie { get; set; }
        public string TypeP { get; set; }
        public Nullable<System.DateTime> DateL { get; set; }
        public string FormattedDateL
        {
            get
            {
                if (DateL.HasValue)
                {
                    return DateL.Value.ToString("yyyy-MM-dd");
                }
                else
                {
                    return string.Empty; // Or any other appropriate value for null dates
                }
            }
        }
        public Nullable<int> Progression { get; set; } = 0;
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
